### ISSUE TITLE
THOR 0.9.7 fail QXcbConnection

### ISSUE THREAD

**Issue by mpi-pebert** [CostaLab/reg-gen#21]
Hi,
I am running THOR 0.9.7 in batch mode on a compute cluster (=headless servers) and my runs fail with the following message:
```bash
QXcbConnection: Could not connect to display
```
Is that coming from the parameter `--report`, i.e., does it try to open the generated HTML report? 
+Peter

**Comment by mpi-pebert** [comment]
Hi Fabio,
thanks for the quick reply. The sys config is as follows:
```bash
Debian 7.11
Linux 3.18.38.1
```
Thor was installed via pip in a Conda environment:
```yaml
name: thor
channels:
  - bioconda
  - conda-forge
dependencies:
  - python=2.7
  - numpy=1.11.0
  - scipy
  - scikit-learn
  - pysam
  - htseq
  - hmmlearn=20151031
  - mpmath
  - cython
  - pip
  - pip:
    - RGT
```
Don't get me wrong - I like tools that output a human readable report (well, haven't seen it so far, but I assume that ;-) ) - if that is indeed the source of the error, I hope there is a solution that lets one keep the report.

I'll try the `export DISPLAY=:0` stuff and report back to you.
